config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  
  get "home/about"
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  #before_action :correct_user, only: [:create, :edit, :destroy]  

  def index
    @friends = Friend.all
    @users = User.all
  end

  def show
  end

  def new
    #@friend = Friend.new
    #@friend = current_user.friends.build(friend_params)
    @friend = current_user.friends.new    
  end

  def edit
  end

  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save 
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: 'no estás autorizado para editar este amig@' if @friend.nil?
  end
  

  private
    def set_friend
      @friend = Friend.find(params[:id])
    end

    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :facebook, :instagram, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
  end
  
  def about
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container">
    <div class="row">
      <div class="col">
      </div>
      <div class="col-6">

        <div class="mb-3">
          <label class="form-label">Firstname</label>
          <%= form.text_field :first_name, class:"form-control", rows:"3" %>
        </div>

        <div class="mb-3">
          <label class="form-label">Lastname</label>
          <%= form.text_field :last_name, class:"form-control", rows:"3" %>
        </div>

        <div class="mb-3">
          <label class="form-label">Email:</label>
          <%= form.text_field :email, class: "form-control", rows: "3", placeholder: "name@example.com" %>
        </div>

        <div class="mb-3">
          <label class="form-label">Phone</label>
          <%= form.text_field :phone, class: "form-control", rows: "3" %>
        </div>

        <div class="mb-3">
          <label class="form-label">Twitter</label>
          <%= form.text_field :twitter, class: "form-control", rows: "3" %>
        </div>

        <div class="mb-3">
          <label class="form-label">Facebook</label>
          <%= form.text_field :facebook, class: "form-control", rows: "3" %>
        </div>

        <div class="mb-3">
          <label class="form-label">Instagram</label>
          <%= form.text_field :instagram, class: "form-control", rows: "3" %>
        </div>

        <div>
          <% if current_user.id > 1 %>
            <%= form.number_field :user_id, id: :friend_user_id, class: "form-control", rows: "3", value: current_user.id, type: :hidden %>
          <% end %>
        <div>      
<br />
        <%= form.submit 'Send', class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
    <div class="col">
    </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

  <p>
    <strong>Twitter:</strong>
    <%= friend.twitter %>
  </p>

  <p>
    <strong>Facebook:</strong>
    <%= friend.facebook %>
  </p>

  <p>
    <strong>Instagram:</strong>
    <%= friend.instagram %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1 class="text-center">Editing friend</h1>

<div class="text-center py-2">
  <%= link_to "Edit", edit_friend_path(@friend), class: "btn btn-lg btn-warning btn-sm" %> |
  <%= link_to "Destroy", @friend, method: :delete, class: "btn btn-lg btn-danger btn-sm" %> |
  <%= link_to "Back", friends_path, class: "btn btn-lg btn-secondary btn-sm" %>
</div>

<%= render "form", friend: @friend %>

<br>

app/views/friends/index.html.erb
<h1 class="text-center">Friends List</h1>

<%= link_to "+", new_friend_path, class: 'btn btn-primary' %>
Soy: <%= current_user.email %>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Name:</th>
      <th scope="col">Email</th>
      <th scope="col">Phone</th>
      <th scope="col">Twitter</th>
      <th scope="col">Facebook</th>
      <th scope="col">Instagram</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
    <tbody>
      <% @friends.each do |friend| %>
        <% if friend.user == current_user %>
          <tr>
            <th scope="row"><%= link_to friend.first_name + ' ' + friend.last_name, friend %></th>
            <td><%= friend.email %></td>
            <td><%= friend.phone %></td>
            <td><%= friend.twitter %></td>
            <td><%= friend.facebook %></td>
            <td><%= friend.instagram %></td>
            <td><%= link_to "Destroy", @friend, method: :delete, class: "btn btn-danger btn-sm" %></td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
</table>

<br />
<br />
<br />
<br />
<br />

app/views/friends/new.html.erb
<h1 class="text-center text-primary">New friend</h1>

<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Back", friends_path, class: 'btn btn-secondary' %>
</div>

app/views/friends/show.html.erb
<main class="container">
  <div class="bg-light p-5 rounded">
    <h2 class="text-primary"><%= @friend.first_name %> <%= @friend.last_name %></h2>
    <hr class="my-4">
    <p class="lead">Email: <%= @friend.email %></p>
    <p>Phone: <%= @friend.phone %></p>
    <p>Twitter: <%= @friend.twitter %></p>
    <p>Facebook: <%= @friend.facebook %></p>
    <p>Instagram: <%= @friend.instagram %></p>
    
    <%= link_to "Edit", edit_friend_path(@friend), class: "btn btn-lg btn-warning btn-sm" %> |
    <%= link_to "Destroy", @friend, method: :delete, class: "btn btn-lg btn-danger btn-sm" %> |
    <%= link_to "Back", friends_path, class: "btn btn-lg btn-secondary btn-sm" %>

  </div>
</main>

app/views/home/about.html.erb
<h2>About us!</h2>
<%= image_tag ("https://cdn.pixabay.com/photo/2016/08/02/23/52/bag-1565402__480.jpg"), class: "d-block w-80", alt: "agenda-vintage" %>

app/views/home/index.html.erb
<main class="container">
  <div class="bg-light p-5 rounded">
    <h2 class="text-dark">Forget the names of your friends and their data?</h2>
    <hr class="my-4">
    <h3>We have the solution!</h3>
  </div>
</main>
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

app/views/layouts/_alerts.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <strong><%= notice %></strong>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <title>Friends-App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css" integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
  </head>

  <body>
    <%= render 'shared/navbar' %>
        <% if notice %>
          <%= render 'layouts/alerts' %>
        <% end %>
        <br />
    <div class="container">
      <%= yield %>
    </div>
        <br />
        <br />
        <br />
        <br />
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class=" text-center text-white " style="background-color:#1A237E;"> 
  <div class="container p-4 pb-0">
    <section class="mb-4">
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-facebook-f"></i
      ></a>
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-twitter"></i
      ></a>
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-google"></i
      ></a>
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-instagram"></i
      ></a>
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-linkedin-in"></i
      ></a>
      <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"
        ><i class="fab fa-github"></i
      ></a>
    </section>
  </div>
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
    © 2022 Copyright:
    <a class="text-white" href="https://mdbootstrap.com/">MDBootstrap.com</a>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark space-between" style="background-color:#1A237E;">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link active' %>
        </li>
        <li class="nav-item">
          <%= link_to 'About', home_about_path, class: 'nav-link' %>
        </li>

        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'Friends', friends_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'New-Friend', new_friend_path, class: 'nav-link' %>
          </li>        
          <li class="nav-item">
            <%= link_to 'Sign-out', destroy_user_session_path, data: { turbo_method: :delete }, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Edit profile', edit_user_registration_path, class: 'nav-link' %>
          </li>    
        <% else %>
          <li class="nav-item">
            <%= link_to 'Sign-in', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Sign-up', new_user_registration_path, class: 'nav-link' %>
          </li>          
        <% end %>  
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>